### ISSUE TITLE
An error has occured while trying to 'Action: SelectGame'

### ISSUE THREAD

**Issue by Sonsalt** [SIXNetworks/withSIX-Platform#224] opened 2016-09-05 14:08 UTC
https://gyazo.com/33aa8cb9020e520b9b083cebfc69a5cf

Happens When:

1. Idle and performing any action after a while (Changing page....)
2. Changing selected Game
3. Clicking on Stream button within the same game while being on mods view

**Comment by sickboy** [comment] 2016-09-05 15:07
Alpha5 fixes this.

**Comment by sickboy** [comment] 2016-09-05 15:54
There's another source of the same error, documented in #225, on the way to be fixed.

**Comment by sickboy** [comment] 2016-09-06 10:54
@Sonsalt the issue is fixed in #225

**Closed** 2016-09-06 20:01 UTC
Labels: ALPHA, bug, Sync, Web interface
